# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blind_date}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ari Epstein"]
  s.date = %q{2010-06-14}
  s.description = %q{Allows you to utilize date calculation functionality of DBMS with a uniform API}
  s.email = %q{aepstein607@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "blind_date.gemspec",
     "lib/blind_date.rb",
     "lib/blind_date/active_record/base.rb",
     "lib/blind_date/active_record/connection_adapters/abstract_adapter.rb",
     "lib/blind_date/active_record/connection_adapters/mysql_adapter.rb",
     "lib/blind_date/active_record/connection_adapters/postgresql_adapter.rb",
     "lib/blind_date/active_record/connection_adapters/sqlite3_adapter.rb",
     "lib/blind_date/active_record/connection_adapters/sqlite_adapter.rb",
     "spec/blind_date_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/aepstein/blind_date}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{DBMS-indepedent methods to query dates in ActiveRecord}
  s.test_files = [
    "spec/blind_date_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.4"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<activerecord>, [">= 2.3.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<activerecord>, [">= 2.3.4"])
  end
end

